### ISSUE TITLE
Website design

### ISSUE THREAD

**Issue by dylanatsmith** [email-markup-consortium/email-markup-consortium.github.io#1]
I've mocked up a first pass of an MVP website based on the [agreed requirements](https://github.com/email-markup-consortium/email-markup-consortium/issues/5):

* Name
* Mission statement
* Contact info
* How to get involved
* Sign-up form to an email list
* Group email for contact info

I’ve also included a contributors list as I think that social proof would lend early credibility to the initiative, but it's optional.

I know this looks like a wireframe. It's intentionally plain: large, clear Arial type, just a few shades of grey, and no strong personality. I figure we should hold off on much colour or style until we decide on a branding direction, but that feels like bikeshedding right now.

### Light mode

![image](https://user-images.githubusercontent.com/6905903/135650368-dcad0eef-f618-48be-827e-ad446be546ea.png)

### Dark mode

![image](https://user-images.githubusercontent.com/6905903/135651381-56d97297-f512-4586-abe6-8df9fdda4968.png)

## Open questions

* Which "how you can help" points do we want to focus on to start? I've included three ideas but there may be something else.
* How will we collect email signups? Can we embed simple form code on GitHub Pages? That would allow us to host here for simplicity.
* Do we want to include a list of contributors (ourselves)? If so, should we allow for adding a job title or other descriptor in addition to (or instead of) a company name?

Any other feedback is welcome as well.

**Comment by Malvoz** [comment]
> Which "how you can help" points do we want to focus on to start? I've included three ideas but there may be something else.

Cross-referencing https://github.com/email-markup-consortium/email-markup-consortium/issues/19 which I believe should be relevant.

**Comment by husseinalhammad** [comment]
Closing this. I'll most likely refer to this concept at a later stage as I like the descriptive approach of the "how you can help" section. Thanks for getting this started, @dylanatsmith
