### ISSUE TITLE
Opengraph and twitter cards missing on website

### ISSUE THREAD

**Issue by rodrigosantander** [email-markup-consortium/email-markup-consortium.github.io#16]
Hi, I noticed something on the consortium website’s opengraph and twitter cards protocols:
https://emailmarkup.org/

- On opengraph, it’s loading parcel’s logo as the main image
- Twitter cards are missing from the code

If you have both of them properly coded on every link, it will help when someone shares the links on fb, on, tw and whatsapp
It’s a small enhancement, but it helps a lot to maintain branding and to a better understanding of what the links are about for people on the net

<img width="564" alt="image-1" src="https://user-images.githubusercontent.com/6817424/178581405-9fe800bc-d7b5-457e-b8da-61740be36ed3.png">
<img width="759" alt="image" src="https://user-images.githubusercontent.com/6817424/178581410-9a0729d2-a0f2-496c-944e-c920937d619a.png">

**Comment by husseinalhammad** [comment]
Thanks @rodrigosantander for pointing this out. This is addressed in #15 which adds the following meta tags:

```html
<!-- OpenGraph Tags -->
<meta property="og:title" content="Email Markup Consortium">
<meta property="og:type" content="article">
<meta property="og:url" content="https://emailmarkup.org/">
<meta property="og:locale" content="en_US">
<meta property="og:image" content="https://emailmarkup.org/img/default-og-image.png">
<meta property="og:image:alt" content="Email Markup Consortium logo">
<meta name="description" property="og:description" content="A community-led group of industry professionals working to improve the email experience for everyone">
<meta property="og:site_name" content="Email Markup Consortium">

<!-- Twitter Tags -->
<meta name="twitter:card" content="summary_large_image">
<meta name="twitter:site" content="EmailMarkup">
<meta name="twitter:title" content="Email Markup Consortium">
<meta name="twitter:description" content="A community-led group of industry professionals working to improve the email experience for everyone">
<meta name="twitter:image" content="https://emailmarkup.org/img/default-og-image.png">
<meta name="twitter:image:alt" content="Email Markup Consortium logo">
```

The `default-og-image.png` is not live yet, but you can see it here:
https://github.com/email-markup-consortium/email-markup-consortium.github.io/pull/15/files#diff-ca8c8149a02f05f6c41f92002d79e0008c314abecfb4515e68530d1b39df13c0

I'll keep this issue open until that PR is merged.
