### ISSUE TITLE
We need a logo

### ISSUE THREAD

**Issue by dylanatsmith** [email-markup-consortium/email-markup-consortium.github.io#2]
We discussed branding being a bit of a blocker to figuring out the visual design for the website. The first step there is a logo (then colours and typefaces).

This is my typical approach to branding projects:
1. Figure out what the brand of this thing even is. Not what it looks like, but what it should evoke. A list of adjectives is a useful output.
2. List, in words, a bunch of ideas for visual concepts. It’s good if the adjectives from point 1 can feed into this. I find mind maps helpful for ideating.
3. Sketch basic ideas.
4. Refine in software (where improvements and new ideas might surface).

In practice, this might look like:

1. The Email Markup Consortium is visionary, connected, etc. 
2. Connectedness leads us to links, chains, overlapping circles... Vision could be an eye.
3. What about an eye with overlapping circles in it? Or some big, solid chain links? Pencil some basic versions on a notepad.
4. That might lead us to ideas like these...

<img width="1167" alt="image" src="https://user-images.githubusercontent.com/6905903/138683468-033af671-3f9b-400a-92f4-cafcfa590379.png">
<img width="854" alt="image" src="https://user-images.githubusercontent.com/6905903/138683573-4d956bb1-0a91-4b2e-978e-4181a54e6f3b.png">

Of course, sometimes you just hit on some way of arranging the name or acronym that looks really cool and that’s fine, too. One trap it’s easy to fall in with the above approach is trying to be too clever and before you know it you’re trying to work in 3 or 4 visual puns and it falls apart as an at-a-glance mark.

Anyway, all this to say: Knowing our mission, let’s start by listing some adjectives for the group.

**Comment by husseinalhammad** [comment]
The [logo](https://drive.google.com/drive/folders/1bUVIrG6TNWAwfTW6FAdypKeJwEpB-8Sf?usp=sharing) has been created. @megbosh and @Wilson110 did a great job on the final version. Thanks for everyone who was involved in the discussion and the early exploratory work.
